# COINGECKO API KEY SETTING
coingecko:
  api_key: example
  api_url: https://api.coingecko.com/api/v3


# MINIO SETTINGS
minio:
  endpoint: example
  access_key: example
  secret_key: example


# AWS SETTINGS
aws:
  region: example
  access_key: example